import os

# Configurable analysis thresholds for Suspicious Pattern Detection (Phase 5)
RAPID_TRANSFER_SECONDS: int = int(os.getenv("RAPID_TRANSFER_SECONDS", "900"))  # 15 minutes
FUND_SPLIT_MIN_DESTINATIONS: int = int(os.getenv("FUND_SPLIT_MIN_DESTINATIONS", "3"))
FUND_CONSOLIDATION_MIN_SOURCES: int = int(os.getenv("FUND_CONSOLIDATION_MIN_SOURCES", "3"))
HIGH_FREQUENCY_WINDOW_MINUTES: int = int(os.getenv("HIGH_FREQUENCY_WINDOW_MINUTES", "60"))
HIGH_FREQUENCY_TRANSACTION_COUNT: int = int(os.getenv("HIGH_FREQUENCY_TRANSACTION_COUNT", "10"))
BURST_TX_PER_MINUTE_THRESHOLD: float = float(os.getenv("BURST_TX_PER_MINUTE_THRESHOLD", "0.5"))
LARGE_TRANSFER_MULTIPLIER: float = float(os.getenv("LARGE_TRANSFER_MULTIPLIER", "3.0"))
LARGE_TRANSFER_MIN_ETH: float = float(os.getenv("LARGE_TRANSFER_MIN_ETH", "1.0"))
MAX_ANALYSIS_HOPS: int = int(os.getenv("MAX_ANALYSIS_HOPS", "5"))
CYCLE_DETECTION_MAX_LENGTH: int = int(os.getenv("CYCLE_DETECTION_MAX_LENGTH", "6"))
UNUSUAL_COUNTERPARTY_COUNT: int = int(os.getenv("UNUSUAL_COUNTERPARTY_COUNT", "8"))

# Configurable thresholds for DeFi & EVM Pattern Detection
MEV_SANDWICH_MIN_PROFIT_ETH: float = float(os.getenv("MEV_SANDWICH_MIN_PROFIT_ETH", "0.005"))
RUG_PULL_MIN_LP_BURN_RATIO: float = float(os.getenv("RUG_PULL_MIN_LP_BURN_RATIO", "0.70"))
PUMP_DUMP_MIN_BUYERS: int = int(os.getenv("PUMP_DUMP_MIN_BUYERS", "3"))
PUMP_DUMP_WINDOW_MINUTES: int = int(os.getenv("PUMP_DUMP_WINDOW_MINUTES", "30"))
WASH_TRADING_MIN_CYCLES: int = int(os.getenv("WASH_TRADING_MIN_CYCLES", "1"))
ORACLE_MANIPULATION_MIN_DRAIN_ETH: float = float(os.getenv("ORACLE_MANIPULATION_MIN_DRAIN_ETH", "0.5"))
FRONT_RUNNING_MIN_GAS_PREMIUM_RATIO: float = float(os.getenv("FRONT_RUNNING_MIN_GAS_PREMIUM_RATIO", "1.10"))
UNLIMITED_APPROVAL_THRESHOLD_WEI: int = int(os.getenv("UNLIMITED_APPROVAL_THRESHOLD_WEI", str(10**50)))
